### ISSUE TITLE
Java client build failed because of RESTException

### ISSUE THREAD

**Issue by Blobonat** [nebulastream/nebulastream-tutorial#7]
Executing `gradle run` results in the following exception:

```
> Task :run FAILED
{"strategyName":"BottomUp","userQuery":"Query::from(\"wind_turbines\").window(TumblingWindow::of(EventTime(Attribute(\"features_properties_updated\")), Minutes(10))).byKey(Attribute(\"metadata_id\")).apply(Sum(Attribute(\"features_properties_mag\"))).sink(FileSinkDescriptor::create(\"/tutorial/java-query-results.csv\",\"CSV_FORMAT\",\"OVERRIDE\"));"}
Exception in thread "main" stream.nebula.exceptions.RESTException: REST API returned error: [statusCode=201, message=]
        at stream.nebula.runtime.NebulaStreamRuntime.executeQuery(NebulaStreamRuntime.java:101)
        at NebulaStreamTutorial.main(NebulaStreamTutorial.java:29)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date
```

The `java-query-results.csv` is created successfully.

**Comment by he-sk** [comment]
Closed with https://github.com/nebulastream/nebulastream-tutorial/commit/416c078fbde0f121f3aa8243e0f1a905f860ae5b
